import { describe, expect, test } from "bun:test";
import { classifyDiffFile, filterDiffFiles } from "../src/diff-filter.ts";

describe("deterministic diff filtering", () => {
  test.each([
    ["pnpm-lock.yaml", "lockfile"],
    ["vendor/acme/library.js", "vendored_dependency"],
    ["web/app.min.js", "minified_or_bundled_asset"],
    ["web/app.bundle.min.js", "minified_or_bundled_asset"],
    ["static/app.0123456789abcdef.js", "minified_or_bundled_asset"],
    ["dist/index.js", "minified_or_bundled_asset"],
    // The motivating pair: shuvbot's own committed bundle and its map.
    ["dist/index.js.map", "source_map"],
    ["packages/action/dist/entry.mjs", "minified_or_bundled_asset"],
    [".next/static/page.js", "minified_or_bundled_asset"],
    ["web/app.js.map", "source_map"]
  ] as const)("filters %s", (path, reason) => {
    expect(classifyDiffFile({ path })).toMatchObject({ accepted: false, reason });
  });

  test.each([
    "build/deploy.js",
    "out/generate-docs.mjs",
    "scripts/dist-check.js",
    "src/distance.ts"
  ])("keeps hand-written %s, since filtering means not reviewing", (path) => {
    expect(classifyDiffFile({ path })).toMatchObject({ accepted: true });
  });

  test("filters files carrying reliable generated markers", () => {
    expect(
      classifyDiffFile({
        path: "src/models.generated.ts",
        patch: "+// Code generated by modelgen. DO NOT EDIT."
      })
    ).toMatchObject({ accepted: false, reason: "generated_file" });
    expect(
      classifyDiffFile({ path: "src/parser.ts", patch: "+// generated helper, edit carefully" })
    ).toMatchObject({ accepted: true });
  });

  test.each([
    "db/migrations/001_add_user.sql",
    "package.json",
    ".github/workflows/release.yml",
    "deploy/app.bundle.js",
    "generated/api/client.ts",
    "src/generated/client.ts",
    "schemas/openapi.json"
  ])("preserves behaviorally relevant %s", (path) => {
    expect(
      classifyDiffFile({ path, patch: "+// Code generated by a tool. DO NOT EDIT." })
    ).toMatchObject({ accepted: true });
  });

  test("does not mistake an unrelated .map data file for a source map", () => {
    expect(classifyDiffFile({ path: "data/world.map" })).toMatchObject({ accepted: true });
  });

  test("partitions files without changing their order or objects", () => {
    const source = { path: "src/index.ts", patch: "+export {}" };
    const lock = { path: "yarn.lock", patch: "+dependency" };
    const result = filterDiffFiles([source, lock]);

    expect(result.accepted).toEqual([source]);
    expect(result.filtered).toEqual([{ file: lock, reason: "lockfile" }]);
  });
});
